### PR TITLE
Dev dwelling ander into Adrian's branch

### PR DESCRIPTION
**Pull request by Arruza17**
There have been quite a few problems when making the report in my virtual machine, what I have done is, from @AdrianPerez09 branch create a branch and run the same code in his virtual machine. It works.
I hope you accept the pool request.

### CODE REVIEW

**Review by yeraysampedro — APPROVED** [review]
Let's hope your report works!

**Review by jorgeccst — APPROVED** [review]
Everything ready to merge!

**Comment by Arruza17** [comment]
> Let's hope your report works!

It's amazing that with the same code in my virtual machine doesn't work and in Adrian's yes :(

**Review by AdrianPerez09 — APPROVED** [review]
Everything fine. Ready to merge.

**Pull request merged**
