### PR TITLE
Deployment Finished

### PR DESCRIPTION
**Pull request by yeraysampedro**
All of the deployment finally working. 

The **_main issues_** found where these:
1.  Imports wrongly ordered
2. Some joins not properly connected
3. Some minor issues with syntax

### CODE REVIEW

**Comment by Arruza17** [comment]
I hate those imports. Ready to merge with master. My classes look fine

**Review by jorgeccst — APPROVED** [review]
Ready to merge

**Review by Arruza17 — APPROVED** [review]
Everything ok again.

**Review by AdrianPerez09 — APPROVED** [review]
Everything fine. Ready to merge.

**Pull request merged**
