### PR TITLE
Dev menu merged into master

### PR DESCRIPTION
**Pull request by Arruza17**
Now everyone can set their own view in the menu. Later on, when you have finished, make a pool request.

### CODE REVIEW

**Review by yeraysampedro — APPROVED** [review]
This branch works in my explotation server, let's merge this into the master

**Review by AdrianPerez09 — COMMENTED** [review]
everything seems to be ready to merge.

**Review by jorgeccst — APPROVED** [review]
Ta bien

**Review by AdrianPerez09 — APPROVED** [review]
everything seems to be ready to merge.

**Pull request merged**
